### ISSUE TITLE
Not working with Check MK Raw 2.2.0p2

### ISSUE THREAD

**Issue by edu8** [MaximilianClemens/checkmk_fritzbox#8]
Hi Maximilian,

Check MK Raw Update 2.2.0p2 is out. When installing the update it says that the fritzbox plugin is not working and will be disabled. This is the  output i get. It would be kind if you could "make it work" again. ;-) Thank you in advance.

Edu8

Executing update-pre-hooks script "01_mkp-disable-outdated"...
-| [fritzbox_smarthome 0.5.8]: Not uninstalling
-| [fritzbox_smarthome 0.5.8]: Updating from 0.5.8
-| [fritzbox_smarthome 0.5.8]: Installed
OK
Executing update-pre-hooks script "02_cmk-update-config"...
-| ATTENTION
-|   Some steps may take a long time depending on your installation.
-|   Please be patient.
-|
-| Verifying Checkmk configuration...
-|  01/04 Rulesets...
-| Failed to load plugin /omd/sites/home8net/local/share/check_mk/web/plugins/wato/parameters_agent_fritzbox_smarthome.py: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| Traceback (most recent call last):
-|   File "/omd/sites/home8net/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 63, in <module>
-|   File "<string>", line 10, in _factory_default_special_agents_fritzbox_smarthome
-| AttributeError: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| Failed to load plugin /omd/sites/home8net/local/share/check_mk/web/plugins/wato/parameters_agent_fritzbox_smarthome.py: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| Traceback (most recent call last):
-|   File "/omd/sites/home8net/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 63, in <module>
-|   File "<string>", line 10, in _factory_default_special_agents_fritzbox_smarthome
-| AttributeError: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| WARNING: Invalid rule configuration detected
-| Ruleset: static_checks:systemd_services
-| Title: Deprecated: Systemd single services
-| Folder: local_network
-| Rule nr: 1
-| Exception: You cannot save this rule. There are no elements defined for this selection yet.
-|
-| You can abort the update process (A) and try to fix the incompatibilities with a downgrade to the version you came from or continue (c) the update.
-|
-| Abort update? [A/c]
-|  02/04 UI extensions...
-| Failed to load plugin /omd/sites/home8net/local/share/check_mk/web/plugins/wato/parameters_agent_fritzbox_smarthome.py: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| Traceback (most recent call last):
-|   File "/omd/sites/home8net/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 63, in <module>
-|   File "<string>", line 10, in _factory_default_special_agents_fritzbox_smarthome
-| AttributeError: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-| Incompatible file 'parameters_agent_fritzbox_smarthome' of extension package 'fritzbox_smarthome 0.5.8'
-| Error: module 'cmk.gui.watolib' has no attribute 'Rulespec'
-|
-| You can abort the update process (A) or disable the extension package (d) and continue the update process.
-| Abort the update process? [A/d]

**Comment by MaximilianClemens** [comment]
Hello @edu8,

thanks for reporting the problem. I'll try to check it the next weekend and deliver a fix.

Regards
Maximilian

**Comment by edu8** [comment]
Hi @MaximilianClemens,

is there still no update?

Regards
Edu8

**Comment by doctore74** [comment]
Hi @MaximilianClemens,

do you have an update on this?

Best regards and thanks for your work,
Christian

**Comment by MaximilianClemens** [comment]
Hi @edu8 and @doctore74 ,
can you try [v0.5.9](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.5.9).

Unfortunately I'm not using Fritz!Dect-Devices anymore, so I can not test if it works 100%.

Regards
Max

**Comment by doctore74** [comment]
Hi @MaximilianClemens, 

thank you for your great work. I talked to Thomas if he could help to migrate this to Checkmk >v2.0.
That escalated quickly ;-) 
The plugin is now fully capable of Fritz devices. Let's say every device I have around for testing.
If you would like to support this please place a link in your repo that an integration for Checkmk can be found here:

https://thl-cmk.hopto.org/gitlab/checkmk/various/fritzbox_smarthome

@edu8 FYI

**Comment by MaximilianClemens** [comment]
Hi,

@doctore74, if he publishes here on github I would archiv my project and link to his.

Regards
Maximilian

**Comment by doctore74** [comment]
I'm pretty sure that he will not do this. 🤷🏼‍♂️

**Comment by edu8** [comment]
Hi @MaximilianClemens,

thanks for your work and sorry for coming back this late. I have tested the newest release v0.5.10 that seems to need CheckMK 2.2.0p17 at least. So i updated my CheckMK to 2.2.0p22 (with a few steps). Now i get a 
`crash failed - please submit a crash report! (Crash-ID: <some id>)`

When opening one service it tells me the following:
`Cannot create graph
Cannot get RRD data for FritzBox.local/Smart Device 17 Thermostat K/ref_temperature
Cannot create graph
Cannot get RRD data for FritzBox.local/Smart Device 17 Thermostat K/temperature_offset`
But the name behind the / at the end of the line varies. It changes at every refresh interval.

I thought, that maybe the historic data may prevent the plugin to work. It tried to delete the rule and create a new one as that helped in the past. I removed the service and recreated it. Nothing seems to help. Do you have a clue on what to do?

**Comment by ggruber** [comment]
Hi Max,

I also have problems with v0.5.10 on CMK 2.2p24

could we try to fix this together?

Best

Gerold

**Comment by MaximilianClemens** [comment]
Link to new Plugin [checkmk_fritzbox_smarthome](https://github.com/MaximilianClemens/checkmk_fritzbox_smarthome).
Tested with cmk 2.4.0. Further development will be in the new repo
